### ISSUE TITLE
No Method to set Application Parameters on Event Hubs messages 

### ISSUE THREAD

**Issue by jseely** [openenergi/go-event-hub#2]
Many applications of Event Hubs use Application Parameters to send metadata with events. There needs to be some method of attaching Application Parameters to the AMQP messages. 

I have a naive implementation that changes the signature of the Send methods here #1

**Comment by tappoz** [comment]
Thank you very much indeed for this :) 

Is there any specific scenario where this is needed? I am thinking at how to test this change to increase the test coverage of the package.

**Comment by jseely** [comment]
Yes, my team has a scenario where all our telemetry flows through the same Event Hub and we use Application Parameters to specify what type of telemetry it is. So in my use case my send looks like this:
```
_, err := sender.Send(string(serializedEvent), map[string]interface{}{
  "Type": "Beats",
  "MessageId": "uuid.NewV4().String(),
  "Timestamp": event.Timestamp.Format("2006-01-02T15:04:05.000+00:00"),
})
```
These metadata properties allow us to not have to crack the blob to figure out what they are on ingest.

**Comment by tappoz** [comment]
It sounds sensible, would it be possible for you to add/change a test checking those application parameters?

**Comment by tappoz** [comment]
I've merged https://github.com/openenergi/go-event-hub/pull/1

I've also pushed some changes to expose the Application Properties for the received message, along with a minimum test coverage. Cf.: https://github.com/openenergi/go-event-hub/commit/d7d688178dae38193f3aef326ab85844d9346aa3

Thanks again for your changes.
